channels:
- defaults
- conda-forge
dependencies:
- python=3.11
- xgboost=1.7.6
- catboost=1.2.7
- scikit-learn=1.6.1
- imbalanced-learn=0.12.4
- pandas=1.5.3
- numpy=1.24.3
- matplotlib=3.10.1
- seaborn=0.13.2
- scipy=1.10.1
- flask=2.2.5
- requests
- joblib
name: airs
